# MuJoCo + ros2_control – FR3 arm controller configuration
controller_manager:
  ros__parameters:
    update_rate: 100            # Hz

    # 启动时自动加载的控制器
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# ------------------------------------------------------------
# joint_state_broadcaster —— 发布 /joint_states
# ------------------------------------------------------------
joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0          # Hz

# ------------------------------------------------------------
# joint_position_controller —— 7-DoF 位置轨迹控制
# ------------------------------------------------------------
joint_position_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      # - effort   ← 去掉这一行，MuJoCoSystem 暂不支持 effort state
