# MuJoCo + ros2_control – FR3 arm controller configuration
controller_manager:
  ros__parameters:
    update_rate: 100            # Hz

    # 启动时自动加载的控制器
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_position_controller:
      type: position_controllers/JointGroupPositionController   # ← 修改

# ------------------------------------------------------------
# joint_state_broadcaster —— 发布 /joint_states
# ------------------------------------------------------------
joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100.0          # Hz

# ------------------------------------------------------------
# joint_position_controller —— 7-DoF 位置轨迹控制
# ------------------------------------------------------------
joint_position_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      # - effort   ← 去掉这一行，MuJoCoSystem 暂不支持 effort state

# ------------------------------------------------------------
# 硬件接口配置（可选，用于调试）
# ------------------------------------------------------------
hardware_interface:
  ros__parameters:
    # 启用调试输出
    debug: true
    # 控制循环频率
    control_frequency: 100.0
