#############################################################################
# fr3_admittance_control.yaml                                              #
#############################################################################

controller_manager:
  ros__parameters:
    # ---------------- controller_manager 自身 ----------------
    update_rate: 1000          # 控制循环频率 (Hz)
    use_sim_time: true         # 使用仿真时间

    # ---------------- joint_state_broadcaster ----------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 100        # 发布频率 (Hz)

    # ---------------- joint_position_controller ----------------
    joint_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      command_interfaces:
        - position

    # ---------------- test_admittance_controller ----------------
    test_admittance_controller:
      type: admittance_controller/AdmittanceController
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      command_interfaces:
        - position
      state_interfaces:
        - position
      chainable_command_interfaces:
        - position
        - velocity

      kinematics:
        plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
        plugin_package: kinematics_interface
        base: base_link
        tip: fr3_link8
        group_name: arm
        alpha: 0.0005

      ft_sensor:
        name: ft_sensor_name
        frame:
          id: fr3_link8
          external: false
        filter_coefficient: 0.005

      control:
        frame:
          id: fr3_link8
          external: false

      fixed_world_frame:
        frame:
          id: base_link
          external: false

      gravity_compensation:
        frame:
          id: fr3_link8
          external: false
        CoG:
          pos:
            - 0.1
            - 0.0
            - 0.0
        force: 23.0

      admittance:
        selected_axes:
          - true
          - true
          - true
          - true
          - true
          - true
        mass:
          - 5.5
          - 6.6
          - 7.7
          - 8.8
          - 9.9
          - 10.10
        damping_ratio:
          - 2.828427
          - 2.828427
          - 2.828427
          - 2.828427
          - 2.828427
          - 2.828427
        stiffness:
          - 214.1
          - 214.2
          - 214.3
          - 214.4
          - 214.5
          - 214.6
