controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

effort_controller:
  ros__parameters:
    joints:
      - slider_to_cart

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: cart_imu
    frame_id: cart_imu
