controller_manager:
  ros__parameters:
    update_rate: 1000 # 控制器管理器的更新频率
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    effort_controller:
      type: effort_controllers/JointGroupEffortController

        
effort_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
